### ISSUE TITLE
Improve Boost build speed

### ISSUE THREAD

**Issue by sergey-shandar** [sergey-shandar/getboost#17]
Stanislaw Szczepanowski: "B2 has this nice param of “-j%NUMBER_OF_PROCESSORS%”. It dramatically speeds up the build. Consider adding that to the boost.cmd script.".

**Comment by travnick** [comment]
According to [documentation](https://boostorg.github.io/build/manual/develop/index.html#bbv2.overview.invocation.options) `-j` defaults to current core count:
```
-j N

    Run up to N commands in parallel. Default number of jobs is the number of detected available CPU threads. Note: There are circumstances when that default can be larger than the allocated cpu resources, for instance in some virtualized container installs.
```

**Comment by chcg** [comment]
@sergey-shandar I could confirm what @travnick said for current boost versions ( at least since 1.69). I think this issue could be closed
