### ISSUE TITLE
Support x64 in the VC100 NuGet package

### ISSUE THREAD

**Issue by bbenoist** [sergey-shandar/getboost#18]
Hi Sergey,

Currently, there is no x64 platform support for [`boost_program_options-vc100`](https://www.nuget.org/packages/boost_program_options-vc100/).

Could you please build and upload it on nuget.org? :pray:

**Comment by bbenoist** [comment]
@sergey-shandar, here is the content of the `boost_program_options-vc100.1.59.0.0` NuGet package:

```
PS> Show-Tree -ShowLeaf C:\src\packages\boost_program_options-vc100.1.59.0.0\
C:\src\packages\boost_program_options-vc100.1.59.0.0\
|--build
|  \--native
|     \--boost_program_options-vc100.targets
|--lib
|  \--native
|     \--address-model-32
|        \--lib
|           |--boost_program_options-vc100-mt-1_59.dll
|           |--boost_program_options-vc100-mt-1_59.lib
|           |--boost_program_options-vc100-mt-gd-1_59.dll
|           |--boost_program_options-vc100-mt-gd-1_59.lib
|           |--libboost_program_options-vc100-mt-1_59.lib
|           |--libboost_program_options-vc100-mt-gd-1_59.lib
|           |--libboost_program_options-vc100-mt-s-1_59.lib
|           |--libboost_program_options-vc100-mt-sgd-1_59.lib
|           |--libboost_program_options-vc100-s-1_59.lib
|           \--libboost_program_options-vc100-sgd-1_59.lib
\--boost_program_options-vc100.1.59.0.0.nupkg
```

The `address-model-64` directory is missing :cry:

**Comment by sergey-shandar** [comment]
Yes, I'm aware about this issue because my home computer (where I build Bosst) has only Express version of Visual C++ 2010. I've planned to deprecate VS 2010 but it appears there are still a lot of customers, even for Visual Studio 2008. Let me check what can I do for you.

**Comment by bbenoist** [comment]
>  I've planned to deprecate VS 2010 but it appears there are still a lot of customers, even for Visual Studio 2008.

Count me in for both.

I see multiple reasons for this:
* Some versions of VS are commercial and small companies might not afford the cost of upgrading.
* As third party commercial compilers and tools (such as Intel C++, Intel Fortran or Resharper) must be upgraded to support a new VS version, some companies might also not afford the cost of upgrading both products.
* Even if you pay for any upgrade, some third party commercial compilers and tools might suffer from a support lag when a new VS version gets released.
* Providing binaries for every build variant of a library is fastidious and not all editors want to spend efforts on it.
* Spending money every year or two on a VS upgrade must be justified. Which can be hard when dealing with non-technical financials.

As an example, my company depends on 3 different VS versions because of poor support from various third parties.

As of now, I have to use:
* VS2008 to build a plugin for a commercial CAD software only supporting this version.
* VS2008 to build another plugin for an opensource visualization software only supporting this version.
* VS2010 on a different project because of a commercial library only supporting this version.
* VS2013+ because of some updates included in the F# compiler.

And it gets even worse when I have to mix such poorly-supported binaries :scream: 

> Let me check what can I do for you.

OK :+1: 
In the meantime I will build it by myself and rely on your version once you fixed it.
Please let me know if you need help and I will try to do my best.

**Comment by sergey-shandar** [comment]
Done in 1.60
