### ISSUE TITLE
NuGet packages for Boost 1.61

### ISSUE THREAD

**Issue by sergey-shandar** [sergey-shandar/getboost#19]

**Comment by gotomanners** [comment]
Hi @sergey-shandar, great to see 1.61 in the works.
Is there a prerelease for this available?
Thanks :)

**Comment by sergey-shandar** [comment]
No. I'm still working on it. I had some problems with VS 2013 on my machine so I can't generate vs120 NuGet packages. I will release 1.61 NuGet packages as soon as I fix it.

**Comment by gotomanners** [comment]
I'm on VS 2015 so I assume no issues there. I'll create a local package and work away until then. 
Thanks

**Comment by sergey-shandar** [comment]
https://github.com/sergey-shandar/getboost/blob/master/releases/1.61.md
