### ISSUE TITLE
Link 1104 Error

### ISSUE THREAD

**Issue by lance0821** [sergey-shandar/getboost#20]
I am working on a project that used libRETS of which boost filesystem is a dependency.I have created a new win32 console application and selected empty project, created a main.cpp file to include librets.h, and installed Boost 1.61 from Nuget, but when building the bare solution I get an error:

Error	LNK1104	cannot open file 'libboost_filesystem-vc140-mt-gd-1_61.lib'

Do I need to download the Boost source distribution and rebuild the library with any additional flags to b2 or can this be easily fixed with a couple settings that may need to be toggled in my project? Thank you help will be appreciated.

**Comment by sergey-shandar** [comment]
Usually, you shouldn't use source libraries. Use [precompiled packages](https://github.com/sergey-shandar/getboost/blob/master/releases/1.61.md#precompiled-libraries) instead. In your case, it should be https://www.nuget.org/packages/boost_filesystem-vc140/1.61.0

**Comment by lance0821** [comment]
Thank you for your help that solved my issue
