### ISSUE TITLE
boost_iostreams_zlib 1.61.0 missing?

### ISSUE THREAD

**Issue by orudge** [sergey-shandar/getboost#21]
Hello,

The boost_iostreams_zlib package published to nuget.org appears to still be on version 1.60.0 - is there a 1.61.0 version available?

**Comment by sergey-shandar** [comment]
It was rename to [boost_iostreams_zlib-src](https://www.nuget.org/packages/boost_iostreams_zlib-src/1.61.0). Sorry for inconvenience. 

See a list of all source libraries here:
https://github.com/sergey-shandar/getboost/blob/master/releases/1.61.md#source-libraries
