### ISSUE TITLE
All src packages are broken.

### ISSUE THREAD

**Issue by sayurin** [sergey-shandar/getboost#22]
For Example, at boost_program_options-src.targets, defined macro is invalid.

    <PreprocessorDefinitions>BOOST_PROGRAM_OPTIONS-SRC_NO_LIB;%(PreprocessorDefinitions)</PreprocessorDefinitions>

`BOOST_PROGRAM_OPTIONS-SRC_NO_LIB` should be `BOOST_PROGRAM_OPTIONS_NO_LIB`.

**Comment by sayurin** [comment]
https://github.com/sergey-shandar/getboost/blob/f1b602fbb784dd041d9b7f7647c08d8e75a1f6cf/builder/builder/SrcPackage.cs#L84-L105

All src packages are define macro "BOOST_<NAME>-SRC_NO_LIB".

**Comment by sergey-shandar** [comment]
Should be fixed in 1.62.0
