### ISSUE TITLE
boost::filesystem missing dependency to boost::system

### ISSUE THREAD

**Issue by peteer22r** [sergey-shandar/getboost#24]
boost::filesystem-vcXXX has a dependency to boost::system-vcXXX
it dose not compile without it
but in nuget package dependency isn't visible, boost::system had be installed manually

**Comment by sergey-shandar** [comment]
It's not a bug, it's a feature :-) In some cases, you don't want to use boost_system-vsXXX NuGet package. For example, if you compile it yourself or use boost_system-src package.

**Comment by peteer22r** [comment]
I don't want to be a nag, but I would expect that one would either use all from nuget or build boost from source. Even if this wouldn't be true, I think most uses that just wan't to use boost:filesytem want just get it with dependencies as simple as possible and nuget package fulfills it. Following Your login, then any nuget package shouldn't have any dependencies because maybe you want to compile it from source. But so as You think.
