### ISSUE TITLE
Request: boost_zlib package

### ISSUE THREAD

**Issue by orudge** [sergey-shandar/getboost#25]
I was able to get boost_iostreams_zlib working following the note in issue #21, but this then introduces a dependency on boost_zlib, which is not available on NuGet. I've taken the liberty of packaging up boost_zlib-vc140 on NuGet as follows:

https://www.nuget.org/packages/boost_zlib-vc140/1.61.0

The binaries are taken from the boost-binaries SourceForge project. However, is it possible that you would be able to add boost_zlib to the packages you create and maintain? I can of course transfer ownership of the NuGet package I've added to you.

Thanks,
Owen.

**Comment by sergey-shandar** [comment]
Hi Owen, the problem with zlib that we also need to specify a version of zlib as well. Which version(s) of zlib we should use? Should we generate only for the latest zlib?

**Comment by orudge** [comment]
It looks like zlib updates are relatively rare these days, so I'd personally just go with the latest version - the SF boost binaries project appears to be doing so too.

**Comment by sergey-shandar** [comment]
Should be fixed now (version 1.62.0)

**Comment by sergey-shandar** [comment]
Hi @orudge,

Could you add me as an owner of the package so I can upload boost_zlib-vc140.1.62.0 ?

**Comment by orudge** [comment]
I believe I added you yesterday when I saw the initial notification here - it says it's "pending approval". If for some reason it's not worked I'll see if I can try it again!

**Comment by sergey-shandar** [comment]
It still shows that you are the only owner of the package https://www.nuget.org/packages/boost_zlib-vc140/

**Comment by orudge** [comment]
I've removed you and readded you. It still says:

sergey.shandar (pending approval)

Is there a control panel somewhere where you can see pending projects or similar?

**Comment by sergey-shandar** [comment]
Thanks, it works this time. I published the 1.62 package.
