### ISSUE TITLE
boost_zlib 1.62.0 package missing include files

### ISSUE THREAD

**Issue by orudge** [sergey-shandar/getboost#28]
Unfortunately the boost_zlib 1.62.0 package appears to be missing the "include" directory (and the zconf.h and zlib.h header files). These were present in my 1.61.0 package.

The lack of them means that an application including boost_iostreams_zlib-src won't build without manually copying over the zlib include files. I can do this if necessary, but I would have thought it should all just work "out of the box".

**Comment by sergey-shandar** [comment]
Hi @orudge,

zlib header files should not be included into Boost Nuget packages. However, there is a separate zlib NuGet package https://www.nuget.org/packages/zlib/ . I've never tried it.
