### ISSUE TITLE
Visual studio 2017 hangs when installing boost 141 through nuget

### ISSUE THREAD

**Issue by Open-Markets-Initiative** [sergey-shandar/getboost#30]
Hope this is the right place.  Love that I can harness boost through nuget.  I was updating to 2017 and the new boost package and it hangs once I get to program options.  I ran it a few times on new projects.

![image](https://cloud.githubusercontent.com/assets/26018443/25285437/db6629ec-267f-11e7-8ca1-b4dc1846e1c9.png)

**Comment by sergey-shandar** [comment]
I couldn't reproduce it. Could you try to remove the files from you packages/ folder. Restart the computer if files are locked.

**Comment by Open-Markets-Initiative** [comment]
Sorry, I didn't see the note.  The issue was due to the version of visual studio, not your package.
