### ISSUE TITLE
boost::locales missing dependency to boost::system

### ISSUE THREAD

**Issue by Evgen25176542** [sergey-shandar/getboost#31]
boost_locale-vc141 does not work, requiring an additional install of boost_system-vc141 and manually add "boost_system-vc141-mt-1_64.lib" to project's Additional Dependencies, with the location of the library file .dll in the root folder of course. Although in the dependencies "boost_locale-vc141" only the "boost" is indicated.

`1>libboost_locale-vc141-mt-1_64.lib(generator.obj) : error LNK2001: unresolved external symbol "class boost::system::error_category const & __cdecl boost::system::system_category(void)" (?system_category@system@boost@@YAABVerror_category@12@XZ) 
1>libboost_locale-vc141-mt-1_64.lib(localization_backend.obj) : error LNK2001: unresolved external symbol "class boost::system::error_category const & __cdecl boost::system::system_category(void)" (?system_category@system@boost@@YAABVerror_category@12@XZ) 
1>libboost_locale-vc141-mt-1_64.lib(lcid.obj) : error LNK2001: unresolved external symbol "class boost::system::error_category const & __cdecl boost::system::system_category(void)" (?system_category@system@boost@@YAABVerror_category@12@XZ) 
1>libboost_locale-vc141-mt-1_64.lib(date_time.obj) : error LNK2001: unresolved external symbol "class boost::system::error_category const & __cdecl boost::system::system_category(void)" (?system_category@system@boost@@YAABVerror_category@12@XZ) 
1>libboost_locale-vc141-mt-1_64.lib(generator.obj) : error LNK2001: unresolved external symbol "class boost::system::error_category const & __cdecl boost::system::generic_category(void)" (?generic_category@system@boost@@YAABVerror_category@12@XZ) 
1>libboost_locale-vc141-mt-1_64.lib(localization_backend.obj) : error LNK2001: unresolved external symbol "class boost::system::error_category const & __cdecl boost::system::generic_category(void)" (?generic_category@system@boost@@YAABVerror_category@12@XZ) 
1>libboost_locale-vc141-mt-1_64.lib(lcid.obj) : error LNK2001: unresolved external symbol "class boost::system::error_category const & __cdecl boost::system::generic_category(void)" (?generic_category@system@boost@@YAABVerror_category@12@XZ) 
1>libboost_locale-vc141-mt-1_64.lib(date_time.obj) : error LNK2001: unresolved external symbol "class boost::system::error_category const & __cdecl boost::system::generic_category(void)" (?generic_category@system@boost@@YAABVerror_category@12@XZ) 
1>E:\Yandex.Disk\Projects\OS\Release\Devs.exe : fatal error LNK1120: 2 unresolved externals`

**Comment by sergey-shandar** [comment]
It's not a bug, it's a feature :-) In some cases, you don't want to use boost_system-vsXXX NuGet package. For example, if you compile it yourself or use boost_system-src package.
