### ISSUE TITLE
Integration of nuget package in an Visual Studio C++CLR dll Project raise linker error

### ISSUE THREAD

**Issue by JackGrinningCat** [sergey-shandar/getboost#32]
Hi, 

thanks for the newest version, I really like how you prepared it. 

I tried to update my boost.1.6.3 to boost.1.6.4. with the help of your nuget package
But i got 
- Error	LNK1104	cannot open file 'libboost_atomic-vc140-mt-gd-1_64.lib'

I didn't understand where this was coming from, but I found it out, ... in some way ...
It's not happening in Normal C++ Projects only in C++/CLR Projects.
Because in some way then the 'libboost_atomic-vc140-mt-gd-1_64.lib' get referenced. How i don't know.

Actually I thought it's only possible by 
- adding the lib file into the project properties, where it wasn't
- with the target file but in none of this it was referenced, 
- I read about #pragma comment(lib, "lib.lib") but i found none *active* in the code base (only 4 commented parts) 

I made a project to test it, 

- [x] MS C++/CLR with Boost.1.64 -> not working Link errors
- [x] MS C++ with Boost.1.64 -> working 
- [x] MS C++/CLR with boost_atomic-vc140.1.64 -> working 

[Boost164.zip](https://github.com/sergey-shandar/getboost/files/959329/Boost164.zip)

I do not know if this is an issue for boost, the right dependencies or visual studio.
Besides boost maintainers itself I wrote here and a message to visual studio (because i couldn't find where the linking happened and that it was nowhere logged).

Well long short. Thanks for reading this.

**Comment by sergey-shandar** [comment]
The Boost NuGet package contains only header files. In some cases, some libraries do not require anything else. But, in other cases, you may need to install additional precompiled or sourced-based NuGet packages. IMHO, in this case, you need to install https://www.nuget.org/packages/boost_atomic-vc140/ .

**Comment by sergey-shandar** [comment]
The complete list of Boost 1.64 NuGet packages is here https://github.com/sergey-shandar/getboost/blob/master/releases/1.64.md

**Comment by JackGrinningCat** [comment]
Hey Sergey, I got it. Thanks
Maybe I just wondered why it changed from 1.63 -> 1.64 .
But nevertheless thanks for your effort.
