### ISSUE TITLE
boost_python3 libraries not built correctly

### ISSUE THREAD

**Issue by lbotsch** [sergey-shandar/getboost#33]
The boost_python3 library uploaded to nuget.org (https://www.nuget.org/packages/boost_python3-vc140/) seems to be compiled against the wrong python version. The libraries

- boost_python3-vc140-mt-1_64.lib
- boost_python3-vc140-mt-gd-1_64.lib

export the symbol

```c++
struct _object * __cdecl boost::python::detail::init_module(char const *,void (__cdecl*)(void))
```

when they should export

```c++
struct _object * __cdecl boost::python::detail::init_module(struct PyModuleDef &,void (__cdecl*)(void))
```

See boost/python/module_init.hpp:

```c++
#  if PY_VERSION_HEX >= 0x03000000
BOOST_PYTHON_DECL PyObject* init_module(PyModuleDef&, void(*)());
#else
BOOST_PYTHON_DECL PyObject* init_module(char const* name, void(*)());
#endif
```

Make sure you actually compile boost_python3 for python3

**Comment by sergey-shandar** [comment]
https://svn.boost.org/trac/boost/ticket/13023

**Comment by sergey-shandar** [comment]
Binaries for 1.64 were taken from https://sourceforge.net/projects/boost/files/boost-binaries/1.64.0/

**Comment by sergey-shandar** [comment]
Switch to [1.65](https://github.com/sergey-shandar/getboost/blob/master/releases/1.65.md) should solve the problem.
