### ISSUE TITLE
boost_python3-vc141 links against python27.dll

### ISSUE THREAD

**Issue by emanuelshalev** [sergey-shandar/getboost#36]
boost_python3-vc141 nugget package links against the wrong version of python (python27.dll when expected to link to python version 3)

**Comment by sergey-shandar** [comment]
Which version?

**Comment by sergey-shandar** [comment]
https://github.com/boostorg/python/issues/129

**Comment by sergey-shandar** [comment]
Please, check Boost 1.66 Nuget package.
