### ISSUE TITLE
boost_locale-vc141 1.65.1 in Visual Studio 2017

### ISSUE THREAD

**Issue by MattiasEppler** [sergey-shandar/getboost#37]
Hi.
To test Message formating and Translation I created a console application and downloaded the nuget package: boost_locale-vc141 1.65.1 and with it the dependencie package boost 1.65.1

If I use the translate Method in the main everything works fine. Until define a variable of generator like in "the first fully localized program" example. Then I get 9  linker errors.

```
Error	LNK2001	unresolved external symbol "class boost::system::error_category const & __cdecl boost::system::generic_category(void)" (?generic_category@system@boost@@YAABVerror_category@12@XZ)	translation	...\libboost_locale-vc141-mt-gd-1_65_1.lib(localization_backend.obj)

Error	LNK2001	unresolved external symbol "class boost::system::error_category const & __cdecl boost::system::generic_category(void)" (?generic_category@system@boost@@YAABVerror_category@12@XZ)	translation	...\libboost_locale-vc141-mt-gd-1_65_1.lib(lcid.obj)

Error	LNK2001	unresolved external symbol "class boost::system::error_category const & __cdecl boost::system::generic_category(void)" (?generic_category@system@boost@@YAABVerror_category@12@XZ)	translation	...\libboost_locale-vc141-mt-gd-1_65_1.lib(date_time.obj)

...
```

**Comment by MattiasEppler** [comment]
I have found a solution but its not clear why.

I have install also nuget package boost_system. But thats not all.
I also have to include <boost/system/system_error.hpp> in my file.

So you have to set the nuget package of boost_locale dependency to boost_system.
And descripe in the help to include the file boost/system/system_error.hpp

**Comment by sergey-shandar** [comment]
Because some users would like to resolve some references manually, and it's not always clear which dependencies could be required, current precompiled packages do not depend on other precompiled packages. You will need to add required packages to your project on demand. For example, for `boost::system` linker errors, you need to install `boost_system` Nuget package.

**Comment by MattiasEppler** [comment]
but how do I know to include boost::system. Only because of linker errors?
and why is it necessary to include <boost/system/system_error.hpp>

**Comment by sergey-shandar** [comment]
>but how do I know to include boost::system. Only because of linker errors?
yes.

>and why is it necessary to include <boost/system/system_error.hpp>
I beleive, it's nothing to do with Boost NuGet packages. You may ask this question here https://github.com/boostorg/boost
