### ISSUE TITLE
Please remove an empty PreprocessorDefinitions from boost.targets

### ISSUE THREAD

**Issue by emptyVoid** [sergey-shandar/getboost#38]
**boost.targets** file contains an _empty_ definition:
```
      <PreprocessorDefinitions>;%(PreprocessorDefinitions)</PreprocessorDefinitions>
```
which prevents preview on the project's Property Pages from showing anything of value:
![image](https://user-images.githubusercontent.com/13639229/34702780-3d38bf6a-f522-11e7-8839-6a2c8007ed72.png)

**Comment by sergey-shandar** [comment]
https://github.com/sergey-shandar/getboost/commit/db104590276913637df3bce85fd851050b61e01d

The fix will be applied in the next version of Boost Nuget packages.
