### ISSUE TITLE
nanosecond resolution libraries?

### ISSUE THREAD

**Issue by prgtrdr** [sergey-shandar/getboost#40]
Sergey,
Thanks so much for providing these nuget packages, they've been really helpful.

For the date_time library, did you compile using the 96 bit resolution for posix_time? Or the standard 64 bit?

**Comment by sergey-shandar** [comment]
@prgtrdr I use binaries from https://dl.bintray.com/boostorg/release/1.66.0/binaries/ so I don't know.
