### ISSUE TITLE
boost python 3 depends on python 2.7

### ISSUE THREAD

**Issue by chcg** [sergey-shandar/getboost#43]
See https://github.com/boostorg/python/issues/129 and https://lists.boost.org/boost-build/2017/12/29715.php. Boost python3 windows packages before boost 1.67 (at least since 1.64) are wrongly build against python 2.7 instead of 3.x.

So e.g. https://www.nuget.org/packages/boost_python3-vc140/ seem to be broken and should contain a hint about this problem.

**Comment by jacktose** [comment]
boostorg/python#129 is closed and apparently fixed as of April.
