### ISSUE TITLE
Why not use official binaries?

### ISSUE THREAD

**Issue by Stannieman** [sergey-shandar/getboost#46]
Why not use the binaries from the 7z or zip file linked to [here](https://www.boost.org/users/download/) and then just pack them in a NuGet?
It saves you the time of building and the hassle of having some machine with all these compilers configured correctly + you know the binaries are exactly the same as the official ones.

**Comment by sergey-shandar** [comment]
getboost already uses these binaries

**Comment by Stannieman** [comment]
Ok @sergey-shandar sorry to bother you in that case.
I assumed you build boost yourself because the readme talks about "Building Boost" and "Run boost.bat. It may take several hours to complete."
