### ISSUE TITLE
Please add support to VS2019 (vc142)

### ISSUE THREAD

**Issue by IRainman** [sergey-shandar/getboost#48]

**Comment by sergey-shandar** [comment]
Official Boost release 1.70 doesn't support VC 14.2. https://www.boost.org/users/history/version_1_70_0.html

**Comment by IRainman** [comment]
Hmm, okay, I already downloaded and compiled boost manually in VS2019, It's worked.

**Comment by sergey-shandar** [comment]
Done for Boost 1.71
