### ISSUE TITLE
Boost 1.70 signals missing

### ISSUE THREAD

**Issue by atidot3** [sergey-shandar/getboost#49]
Hi there,

Wanted to upgrade by boost 1.68 to 1.70.
Seems nuget are missing from the repository.

Unable to resolve dependencies. 'boost 1.70.0' is not compatible with 'boost_signals-vc141 1.68.0 constraint: boost (= 1.68.0)'.

**Comment by sergey-shandar** [comment]
Boost Signal is removed from Boost framework in version 1.69: https://www.boost.org/users/history/version_1_69_0.html#version_1_69_0.discontinued_libraries
