### ISSUE TITLE
missing boost_unit_test_framework-vc142

### ISSUE THREAD

**Issue by janwilmans** [sergey-shandar/getboost#51]
Hi, I'm updating from boost 1.69 to 1.70 but I noticed there is no boost_unit_test_framework-vc142 on nuget, while it was there in previous releases? Was this a conscious choice or a missed package?

**Comment by aarotech** [comment]
I'm having the same problem.  Any word on this would be appreciated.

**Comment by sergey-shandar** [comment]
Boost 1.71 has it.
