### ISSUE TITLE
LNK1104	cannot open file 'libboost_date_time-vc142-mt-gd-x32-1_71.lib'

### ISSUE THREAD

**Issue by assafwo1** [sergey-shandar/getboost#53]
i'm using vs 2019

Microsoft Visual Studio Community 2019
Version 16.3.8
VisualStudio.16.Release/16.3.8+29503.13
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA826
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.3.286.43615
ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0   16.3.286.43615
Azure App Service Tools v3.0.0

C# Tools   3.3.1-beta3-19461-02+2fd12c210e22f7d6245805c60340f6a34af6875b
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   5.3.1
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

Visual Basic Tools   3.3.1-beta3-19461-02+2fd12c210e22f7d6245805c60340f6a34af6875b
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.3.0-beta.19455.1+0422ff293bb2cc722fe5021b85ef50378a9af823
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

i used nuget manager to get package: 

Attempting to gather dependency information for package 'boost.1.71.0' with respect to project 'managed_shared_memory', targeting 'native,Version=v0.0'
Gathering dependency information took 74.89 ms
Attempting to resolve dependencies for package 'boost.1.71.0' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'boost.1.71.0'
Resolved actions to install package 'boost.1.71.0'
  GET https://api.nuget.org/v3-flatcontainer/boost/1.71.0/boost.1.71.0.nupkg
  OK https://api.nuget.org/v3-flatcontainer/boost/1.71.0/boost.1.71.0.nupkg 140ms
Installing boost 1.71.0.
Adding package 'boost.1.71.0' to folder 'C:\Users\assafw\source\repos\managed_shared_memory\packages'
Added package 'boost.1.71.0' to folder 'C:\Users\assafw\source\repos\managed_shared_memory\packages'
Added package 'boost.1.71.0' to 'packages.config'
Successfully installed 'boost 1.71.0' to managed_shared_memory
Executing nuget actions took 1.79 min
Time Elapsed: 00:01:47.6128941
========== Finished ==========

**Comment by assafwo1** [comment]
https://stackoverflow.com/questions/13042561/fatal-error-lnk1104-cannot-open-file-libboost-system-vc110-mt-gd-1-51-lib

**Comment by sergey-shandar** [comment]
Some libraries require additional precompiled binaries. You can find NuGet packages with precompiled headers here https://github.com/sergey-shandar/getboost/blob/master/releases/1.71.md#precompiled-libraries. For example, for `system` and VC14.2 you will need to install https://www.nuget.org/packages/boost_system-vc142/1.71.0

**Comment by assafwo1** [comment]
i just need boost-interprocess. what the fastest way to get it?

**Comment by sergey-shandar** [comment]
It looks like `interprocess` has no binaries. I suspect, you need to install `boost` NuGet packages, start to use `interprocess` in your code and then install all additional dependencies according to your linker errors.
