### ISSUE TITLE
1.72?

### ISSUE THREAD

**Issue by kanstantsin-chernik** [sergey-shandar/getboost#55]
Hey, There is a new version. Can't wait to upgrade

**Comment by chcg** [comment]
@sergey-shandar Do you have a schedule when 1.72 will be available? Thanks.

**Comment by chcg** [comment]
@sergey-shandar @kanstantsin-chernik Could be closed as 1.72 is available with https://github.com/sergey-shandar/getboost/commit/6cb91378b1bd698f68b404539ab00a423fb514f0 and nuget https://www.nuget.org/packages/boost/1.72.0
