### ISSUE TITLE
Boost 1.73

### ISSUE THREAD

**Issue by gummif** [sergey-shandar/getboost#57]
A new version was released in april, any change of an update? https://www.boost.org/users/history/version_1_73_0.html

**Comment by chcg** [comment]
@sergey-shandar In the meantime also https://www.boost.org/users/history/version_1_74_0.html is available.

**Comment by chcg** [comment]
And now also https://www.boost.org/users/history/version_1_75_0.html.

**Comment by gummif** [comment]
We gave up, are now using the conan package manager.

**Comment by sergey-shandar** [comment]
@gummif I'm sorry that I was not able to update the packages for about one year. Honestly, other package managers (like conan or [vcpkg](https://github.com/Microsoft/vcpkg)) could be better for C++ than nuget.
