### ISSUE TITLE
Boost 1.75

### ISSUE THREAD

**Issue by vistart** [sergey-shandar/getboost#60]
A new version was released in april, any change of an update? https://www.boost.org/users/history/version_1_75_0.html

**Comment by chcg** [comment]
@sergey-shandar If I could support you in releasing the version 1.73 to 1.75 just let me know.

**Comment by chcg** [comment]
@sergey-shandar 1.76 is released. Probably you have to check how to adapt to the change for regex to be header only:

> Regex:
> 
>     Regex is now header only except in C++03 mode.
>     Support for C++03 is now deprecated.
>     The library can now be used "standalone" without the rest of Boost being present.

**Comment by sergey-shandar** [comment]
I will release 1.76. If one of the Boost library is a header-only then you only need to depend on the main Boost NuGet package.
