### ISSUE TITLE
VC143 support

### ISSUE THREAD

**Issue by ctrysbita** [sergey-shandar/getboost#63]
Visual Studio 2022 has been released with vc143.

**Comment by chcg** [comment]
@ctrysbita https://www.nuget.org/packages/boost-vc143 is available since boost 1.78.0
@sergey-shandar V143 is not linked from main readme.md. Apart from that this issue is resolved.
Boost 1.79.0 is available https://www.boost.org/users/history/version_1_79_0.html

**Comment by sergey-shandar** [comment]
Fixed
