### ISSUE TITLE
License Clarification

### ISSUE THREAD

**Issue by damyanp** [sergey-shandar/getboost#64]
I was wondering if you could clarify what license older versions of the nuget package are under.  If I go to nuget.org all the packages point to this repo, which means that they currently say that they're under the BSL.

However, sites such as https://clearlydefined.io/definitions/nuget/nuget/-/boost/1.76.0 list the license as Apache 2.0, as they have a policy of looking at the license file at the time the package was published.

Can you provide any guidance as to which license these older releases should be considered to be under?

Thanks!

**Comment by sergey-shandar** [comment]
It was my mistake to use Apache-2.0 for this project. I can't republish the old packages but I'm ok if it is used under BSL.
